# Generated by Django 3.2.10 on 2021-12-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'diagnose',
                'verbose_name_plural': 'Diagnoses',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('diagnoses', models.ManyToManyField(related_name='patients', to='patients.Diagnose', verbose_name='diagnoses')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
