# Generated by Django 3.2.10 on 2021-12-20 20:11

from django.db import migrations, models
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20211220_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[patients.validators.validate_date_of_birth_no_future, patients.validators.validate_date_of_birth_max_age], verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, related_name='patients', to='patients.Diagnose', verbose_name='diagnoses'),
        ),
    ]
